name: 'Check CodeQL Status'
description: 'Check the status of CodeQL analysis'
inputs:
  token:
    description: 'GitHub token'
    default: ${{ github.token }}
    required: true
  pr_number:
    description: 'Pull request number'
    default: ${{ github.event.pull_request.number }}
    required: true
  repo:
    description: 'Repository'
    default: ${{ github.repository }}
    required: true
runs:
  using: 'composite'
  steps:
    - run: chmod +x ${{ github.action_path }}/run.sh
      shell: bash
    - run: ${{ github.action_path }}/run.sh "${{ inputs.token }}" "${{ inputs.pr_number }}" "${{ inputs.repo }}"
      shell: bash